// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using LootGoblin.Bot.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LootGoblin.Bot.Data.CompiledModels
{
    public static class EventParticipantUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(EventParticipant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventId>k__BackingField")]
        public static extern ref int EventId(EventParticipant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExcludedFromLoot>k__BackingField")]
        public static extern ref bool ExcludedFromLoot(EventParticipant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TotalParticipation>k__BackingField")]
        public static extern ref TimeSpan TotalParticipation(EventParticipant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref ulong UserId(EventParticipant @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Event>k__BackingField")]
        public static extern ref GuildEvent Event(EventParticipant @this);
    }
}
