// <auto-generated />
using LootGoblin.Bot.Data;
using LootGoblin.Bot.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(EventDbContext), typeof(EventDbContextModel))]
