// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using LootGoblin.Bot.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LootGoblin.Bot.Data.CompiledModels
{
    public static class GuildSettingsUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref ulong Id(GuildSettings @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventChannelId>k__BackingField")]
        public static extern ref ulong? EventChannelId(GuildSettings @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventOrganizerRoleId>k__BackingField")]
        public static extern ref ulong? EventOrganizerRoleId(GuildSettings @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventParticipantRoleId>k__BackingField")]
        public static extern ref ulong? EventParticipantRoleId(GuildSettings @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LootChannelId>k__BackingField")]
        public static extern ref ulong? LootChannelId(GuildSettings @this);
    }
}
