// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using LootGoblin.Bot.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LootGoblin.Bot.Data.CompiledModels
{
    public static class GuildEventUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompletedAt>k__BackingField")]
        public static extern ref DateTimeOffset? CompletedAt(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompletedBy>k__BackingField")]
        public static extern ref ulong? CompletedBy(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedBy>k__BackingField")]
        public static extern ref ulong CreatedBy(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CurrentState>k__BackingField")]
        public static extern ref EventStatus CurrentState(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GuildId>k__BackingField")]
        public static extern ref ulong GuildId(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaximumParticipants>k__BackingField")]
        public static extern ref int? MaximumParticipants(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MessageId>k__BackingField")]
        public static extern ref ulong? MessageId(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MinimumParticipantMinutes>k__BackingField")]
        public static extern ref int? MinimumParticipantMinutes(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OriginChannelId>k__BackingField")]
        public static extern ref ulong? OriginChannelId(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StartedAt>k__BackingField")]
        public static extern ref DateTimeOffset? StartedAt(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StartedBy>k__BackingField")]
        public static extern ref ulong? StartedBy(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventParticipants>k__BackingField")]
        public static extern ref ICollection<EventParticipant> EventParticipants(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LootPiles>k__BackingField")]
        public static extern ref ICollection<LootPile> LootPiles(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParticipantChannels>k__BackingField")]
        public static extern ref ICollection<GuildEventChannel> ParticipantChannels(GuildEvent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParticipantSessions>k__BackingField")]
        public static extern ref ICollection<ParticipantSession> ParticipantSessions(GuildEvent @this);
    }
}
