// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using LootGoblin.Bot.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LootGoblin.Bot.Data.CompiledModels
{
    public static class LootPileUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompletedAt>k__BackingField")]
        public static extern ref DateTimeOffset? CompletedAt(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CompletedBy>k__BackingField")]
        public static extern ref ulong? CompletedBy(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedBy>k__BackingField")]
        public static extern ref ulong CreatedBy(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CurrentStatus>k__BackingField")]
        public static extern ref LootStatus CurrentStatus(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventId>k__BackingField")]
        public static extern ref int EventId(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LootType>k__BackingField")]
        public static extern ref LootType LootType(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MessageId>k__BackingField")]
        public static extern ref ulong? MessageId(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OriginChannelId>k__BackingField")]
        public static extern ref ulong? OriginChannelId(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RollType>k__BackingField")]
        public static extern ref LootRollType RollType(LootPile @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Event>k__BackingField")]
        public static extern ref GuildEvent Event(LootPile @this);
    }
}
