// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using LootGoblin.Bot.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LootGoblin.Bot.Data.CompiledModels
{
    public static class ParticipantSessionUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(ParticipantSession @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChannelId>k__BackingField")]
        public static extern ref ulong ChannelId(ParticipantSession @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EndedAt>k__BackingField")]
        public static extern ref DateTimeOffset? EndedAt(ParticipantSession @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventId>k__BackingField")]
        public static extern ref int EventId(ParticipantSession @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EventParticipantId>k__BackingField")]
        public static extern ref int? EventParticipantId(ParticipantSession @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StartedAt>k__BackingField")]
        public static extern ref DateTimeOffset StartedAt(ParticipantSession @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref ulong UserId(ParticipantSession @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Event>k__BackingField")]
        public static extern ref GuildEvent Event(ParticipantSession @this);
    }
}
